// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('htmlIframe');

  app.service('StepTests', function($rootElement) {
    return {
      tests: [
        {
          name: "The paragraph element has a bold tag child element.",
          fn: function() {
            return $('body>p>b').length > 0;
          }
        }, {
          name: "The bold element contains the content 'contacts'",
          fn: function() {
            return $('body>p>b').html() === "contacts";
          }
        }, {
          name: "Body has an h3 element",
          fn: function() {
            return $('body>h3').length > 0;
          }
        }, {
          name: "H3 element is the third child of body",
          fn: function() {
            return $('body').children()[2].tagName === "H3";
          }
        }, {
          name: "The h3 element contains an i element ",
          fn: function() {
            return $('body>h3>i').length > 0;
          }
        }, {
          name: "The i element contains the content 'John Doe'",
          fn: function() {
            return $('body>h3>i').html() === "John Doe";
          }
        }
      ],
      run: function() {
        return console.log("RUNNING TESTS");
      }
    };
  });

}).call(this);
