// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('htmlIframe');

  app.service('StepTests', function($rootElement) {
    return {
      tests: [
        {
          name: "H1 has one class 'jumbotron'",
          fn: function() {
            return $('body>h1').prop('class') === 'jumbotron';
          }
        }, {
          name: "LI exists with an id of '31'",
          fn: function() {
            return $("li#31").length > 0;
          }
        }, {
          name: "LI #31 has one class: 'recent-contact'",
          fn: function() {
            return $("li#31").prop('class') === 'recent-contact';
          }
        }, {
          name: "LI #31 has content 'Mary Smith'",
          fn: function() {
            return $.trim($('li#31').html()) === "Mary Smith";
          }
        }
      ],
      run: function() {
        return console.log("RUNNING TESTS");
      }
    };
  });

}).call(this);
