// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('htmlIframe');

  app.service('StepTests', function($rootElement) {
    return {
      tests: [
        {
          name: "has a BODY tag",
          fn: function() {
            return $('BODY').length > 0;
          }
        }, {
          name: "has a HEAD tag",
          fn: function() {
            return $('HEAD').length > 0;
          }
        }, {
          name: "has at least one H3 tag",
          fn: function() {
            return $('H3').length > 0;
          }
        }
      ],
      run: function() {
        return console.log("RUNNING TESTS");
      }
    };
  });

}).call(this);
